### ISSUE TITLE
[BUG]: Calendar does not respect Theme.palette.white as background

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#159]
**Describe the bug**
Calendar needs to use the Theme.palette.white as the background to match theme, or allow for transparent background so it can be embedded in apps that are not white

**To Reproduce**
1. Generate a theme with the background color any other than white and add to a new app from scratch
2. Add calendar component to app and assign Theme property to the theme

**Expected behavior**
Calendar background matches the background color in the app

**Actual behavior**
Background color of calendar component is white

**Screenshots**
![image](https://user-images.githubusercontent.com/43950360/196017066-39fba443-4732-4987-a9eb-7e86c6b3aa3e.png)

**Additional context**
Respecting theme or allowing for transparent background would work

**Comment by Ramakrishnan24689** [comment]
Hi @denisem-msft,
Calendar component of Fluent UI is transparent by nature, i.e. we can observe other elements beneath it while using in Canvas App as a code component. I believe it is due to the fact that it is primarily used as part of Datepicker.
Hence a white color which is one of the background property value is provided. App makers can remove this color to make it transparent or use Palette colors(From theme ThemeJSON) as per their needs.

![image](https://user-images.githubusercontent.com/11135056/196017795-6d82cedd-b630-49d5-b87f-5e5d2ec4b9b9.png)

**Comment by denisem-msft** [comment]
Thanks @Ramakrishnan24689 - the issue was happening when there was a Theme applied to the calendar, it doesn't respect the background color and was rendering as white and seems to be transparent without the Theme applied. Ideally, I would want to have today's date and month highlight colors match the theme. 

A workaround could be to apply the Theme to the calendar and update the Background color with the correct color (which I confirmed works) - documenting here for others' awareness.

**Comment by denisem-msft** [comment]
Closing as this is working as expected
