### ISSUE TITLE
BUG/Feature Reqest: Details List won't display Lookup Column

### ISSUE THREAD

**Issue by medoomi** [microsoft/powercat-creator-kit#197]
**Describe the bug (maybe a feature request)**
When Details List is connected to a DataVerse source, it doesn't display a lookup column (at least I couldn't figure out the syntax within columns_Items to get the lookup column to display).

**Comment by scottdurow** [comment]
Hi! To get lookup columns to show the name of the related record - you will need to include the related table in your data sources for the app and then refesh. 

For example if you are displaying Accounts and showing a lookup column to the primary contact, you'll need to include the Contact table in the app data sources as well as Accounts. 

Hope this helps.

**Comment by medoomi** [comment]
Thank you so very much for the reply.  Sadly the related tables are already added in the app (& refreshed). I am guessing it is my syntax then...

Within the columns_Items property and within the table, I have tried the following using the schema name:
`    {
        ColName: "cra6a_sectionarea.cra6asectionarea", ColDisplayName:"Section Area", ColSortable:true, ColWidth:150, ColRowHeader:true, ColResizable:true
    },`

I have also tried using the display name:
`    {
        ColName: "'Section Area'.'Section/Area'", ColDisplayName:"Section Area", ColSortable:true, ColWidth:150, ColRowHeader:true, ColResizable:true
    },`

Is there something amiss with my syntax?

**Comment by scottdurow** [comment]
Hi @medoomi!

Ok - thanks for the update!

Could you try:
1. Making sure that the Section Area column is in the selected 'Fields' for the Details List
2. Change the ColName to be the logical name of the lookup column - so in your case it could be cra6a_sectionarea (without the 'dot')

So, in my example before where you are showing the Primary Contact for an Account, the Fields must include the Primary Contact field, and then the column would look similar to: `{ ColName: "primarycontactid", ColDisplayName:"Primary Contact", ColWidth:150}`

Thanks!
Scott

**Comment by medoomi** [comment]
Thank you again so much @scottdurow 

Apologies for catching you on Thanksgiving... feel free to reply whenever it suits.

Using the schema name of the columns within the (primary) data source pulls records into the Details List `{ColName: "cra6a_SectionArea", ColDisplayName:"Section Area", ColSortable:true, ColWidth:150, ColRowHeader:true, ColResizable:true},` but it pulls the autonumber (the primary name column) of the referenced lookup table.

- Is there any other way to specify a different column in the lookup table than the primary name column? (maybe this is a feature request?)

**Comment by scottdurow** [comment]
Ah right - I see.

You could use AddColumns to add a custom column using an expression that gets the related record column value, and then reference that custom column instead of the table column.

Once you use AddColumns however, you will need to handle delegated paging and sorting external to the control. You can do this using the technique I show here https://youtu.be/zfyoBLbPvoQ

Alternatively you could add a calculated column or formula column in the dataverse table to pull in the related column value, and use that in the grid. 

https://learn.microsoft.com/en-us/power-apps/maker/data-platform/formula-columns

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/calculated-rollup-attributes#calculated-columns


Hope this helps!

**Comment by medoomi** [comment]
Thanks so much @scottdurow  Took a while to digest, but I think I get it.

It would be great in the future if a lookup column could be manipulated directly from the Details List to show the applicable related column :-)
