### ISSUE TITLE
[BUG]: DetailList (1.0.19) TotalPages doesn't count correctly

### ISSUE THREAD

**Issue by jean-goyat** [microsoft/powercat-creator-kit#308]
**Describe the bug**
Similar/related to bug #148 , _TotalPages_ property of the _DetailList_ returns -1 instead of... a positive integer

**To Reproduce**

1. Create & Populate **DetailList** (with _Items:_ Sequence(100)_ for example)
2. Turn on _Pagination for Large Datasets_
3. Set the _Page Size_ to 10
4. Build controls to control pagination and set _InputEvent_ of the _DetailList_ accordingly

**Expected behavior**
The _TotalPages_ property should return a number >0 but returns -1 as soon as the user interacts with the list in any way
(_PageNumber_ calculates as expected)

**Screenshots**
![image](https://user-images.githubusercontent.com/50023372/226408113-9f50c8eb-e714-44a0-89a5-5538b944d336.png)

**Comment by scottdurow** [comment]
Hi @jean-goyat - This is actually by design due to a limitation of the Power Apps Component Framework not providing the total number of records for datasets beyond the delegation limit. 

Once you turn on `LargeDatasetPaging`, you will be able to page beyond this limit, but you will need to perform your own delegated record page count using the technique I show here https://youtu.be/zfyoBLbPvoQ

You would only need to use this setting if you need to page through large numbers of records.

Hope this helps,
Scott

**Comment by jean-goyat** [comment]
Appreciate the response and thanks for the video, I'll try work without the large `LargeDatasetPaging` option. I'll close this issue
