### ISSUE TITLE
[Creator Starter Kit] BUG: Fluent Details List (0.0.20) is not rendering index to Zero after unrelate items

### ISSUE THREAD

**Issue by yaseralhosani** [microsoft/powercat-creator-kit#37]
**Describe the bug**
As both tables are using different data sources from Dataverse, there are 1:N relationships. When I unrelate items, the index is not set to zero after unrelated items.

**Example Scenario**
There are two FluentDetailsList_A and FluentDetailsList_B, with FluentDetailsList_B using Item = _FluentDetailsList_A .Selected.'Other Source'.Name_.

The rendering is fine when using ForAll Relate Functions to add related items in FluentDetailsList_B, but I have issues when using ForAll Unrelate Functions. FluentDetailsList_B does not render the index to Zero after unrelate selected items. Let's say If I select 4 Items in FluentDetailsList_B to unrelate items, it will be 4 Items in the index as the last value in FluentDetailsList_B until I select other records in FluentDetailsList_B, then it will fix it as the current total number selected records.

**Comment by scottdurow** [comment]
Hi @yaseralhosani - thank you for submitting this and describing the issue description.
Just so I can be sure I understand fully, could you share a simple solution that demonstrates the issue?

**Comment by scottdurow** [comment]
Hi @yaseralhosani - Thank you for this. Although I can't import this solution because it doesn't have the tables included - I can see the Power Fx code you are using from unpacking the app. I'll look into your sceario and run some tests.

In the meantime, you may want to try without using the navigation property `fdlStrategicObjectivesDataSO.Selected.'Strategic Key Performance Indicators'` - instead `Filter` the sub-grid using the primary key of the `'Strategic Objectives'` table.

E.g if you were going to filter a sub grid to only show the related contacts for a selected `Account` in `fdlAccounts`, you would bind the contacts grid items to be:
```
Items = Filter(Contacts,AsType('Company Name',[@Accounts]).Account = fdlAccounts.Selected.Account)
```
The `AsType` wouldn't be needed in your scenario assuming you don't have a polymorphic relationship.

Additionally, after you have performed the `Relate` and `Unrelate` operations, use `Referesh('Strategic Key Performance Indicators')` to get the latest values.

Once I have more information on using the navigation property as a data source, I'll update this issue.

FYI - There is also an issue that will be fixed in the July release where the selection is cleared after the grid is refreshed/filtered.

Thank you for helping with the Creator Kit!

**Comment by yaseralhosani** [comment]
Hi @scottdurow,

I really appreciate your reply.

It was my fault that I did not provide a proper solution 😥.

Based on my scenario, the subgrid is working great so far. Thanks for reminding me about polymorphic relationships (I had forgotten about this). 

In addition to what you mentioned in your last comment, there is an issue where the selection is cleared after the grid is refreshed/filtered. In addition, I noticed subgrid selections when to relate and unrelate are refreshed and able to get the latest values without using the Refresh function because it's already linked with the first grid (If my guess was right), but selections in the subgrid were not cleared until I select one or more items in the subgrid then it will count one or more based on a number of selections in the subgrid.

Thank you and I really appreciate it and I can't wait for the July release 😀

**Comment by denisem-msft** [comment]
@yaseralhosani can you please confirm if the refresh behavior you were looking for was resolved in the July update?

**Comment by yaseralhosani** [comment]
> @yaseralhosani can you please confirm if the refresh behavior you were looking for was resolved in the July update?

I will check and update.

**Comment by yaseralhosani** [comment]
@denisem-msft As expected, it now works perfectly.

**Comment by denisem-msft** [comment]
Thank you for validating.
