### ISSUE TITLE
[DetailsList] | Setting Font and/or Font Size

### ISSUE THREAD

**Issue by sperry1625** [microsoft/powercat-creator-kit#48]
I would like to be able to set the font and font size used for the DetailsList control.  There are no properties exposed that will allow me to do that.  The control has a theme property, which I use, but the theme only contains colors, not font selections.

Is there another way to set these? I checked the documentation and did not see anything. Other controls have Font properties, why not this one?

I did not see this listed in the backlog.

Thank you.

**Comment by denisem-msft** [comment]
Hello @sperry1625 - This is by design that we're not changing font and font size to stay consistent with the Fluent UI guidelines. However, in the columns property you can add the following bool property to slightly adjust the text size.

`ColRowHeader` - Defines a column to render larger than the other cells (14px rather than 12px). There normally would only be a single Row Header per column set.
See full docs here: https://github.com/microsoft/powercat-code-components/tree/main/DetailsList

**Comment by sperry1625** [comment]
Thank you, that helped.
