### ISSUE TITLE
[BUG]: Details List ignores sort order of data in items

### ISSUE THREAD

**Issue by jh-sigmadx** [microsoft/powercat-creator-kit#483]
**Describe the bug**
The Details List no longer shows the data as it is sorted in the "items" collection and will only list the data in the "default" sort order.
The Formula in the PowerApps Studio shows the list items in the correct sort order, but the Details List only shows the default Sort Order.

The issue only occurs in Studio Authoring version v3.24073 and above.
reverting to Studio Authoring version v3.24072 solves the issue, and the Details List shows the correct sorting again.

AB#3883

**Comment by datalink0** [comment]
Also experiencing this issue. Updated to the latest CreatorKit solution, but problem still persists. Temporary fix seems to be reverting to an earlier Studio Authoring version.

**Comment by Dohsan** [comment]
We are also experiencing this and several other issues on the fluentdetailslist

We are using external paging and sorting on the details list using a gallery as the source. The gallery is sorted correctly as is the items property of the fluentdetails; however, the data being rendered is different and not in the correct sorting order. The data is changing when toggling the sort, just not sense of an actual order to it.

**Comment by rarattay** [comment]
Hi, We are aware of this issue impacting the sorting order of datasets in controls such as the Details List and are working to deploy a fix soon. In the meantime, please revert back to Canvas studio version v3.24072 or older to fix this issue.

**Comment by jh-sigmadx** [comment]
Thanks rarattay, 
I can only imagine what it's like to build PCF style components, when the PowerApps Team keep changing the PCF protocols!
(Reading around, the same update broke many custom controls people were working on...)

For other devs finding their way here - I've found that "&studio-version=v3.24072.6.302069373" (appended to the studio URL) is the latest build that still works with the Details List at the moment. J.

**Comment by OliverDumrique** [comment]
Hi, we've listed this known issue that will update once the fix deploys: https://admin.powerplatform.microsoft.com/knownissues/4238060

**Comment by OliverDumrique** [comment]
The fix has been deployed, please verify and close the bug when you can.

**Comment by tmorg555** [comment]
I'm still getting no sorting behavior on the Details List component. I updated to the latest release of Creator Kit.

I was only able to regain the correct sorting by using the "&studio-version=v3.24072.6.302069373" URL append.

**Comment by jh-sigmadx** [comment]
@tmorg555 
FYI - I have found that the latest PowerApps Studio build that still works with the PCF Components is:
v3.24074.18.305760871 - 14th August 2024

**Comment by Reinhard-S** [comment]
Hi @rarattay,

Could you please help us clarifying if there was a recent update which potentially could have fixed the sorting issue? 
I did some error analysis for one of our customers yesterday and noticed that the issue seems to be resolved today.

Additionally, today a new warning message pops up in Power Apps Studio, see below:

![image](https://github.com/user-attachments/assets/bbf51310-d12c-48b2-8bd0-dec8e4622ac9)

Investigating further, we found that Power Apps Studio creates new fields within the Fluent Details List exactly with the type mentioned in the screenshot, whereas previously, all existing columns have been created as "Control: PcfDataField" inside the component's YAML.

Due to the message displayed at startup I assume that the wrong definition is generated by Power Apps Studio, could you please provide insights on this? For the time being, I advised my client to copy the code of the existing component into notepad, replace the definition string "cat_PowerCAT.FluentDetailsListTemplate_dataField" by "PcfDataField", and paste the altered definition of the control back into the canvas app, replacing the original control.

Please advise if that approach is fine, and please also let us know if here's anything else we can do to avoid such problems in future.

Thank you,
Best Regards,
Reinhard

**Comment by jh-sigmadx** [comment]
@rarattay 

I think you're a little out of date - this _was_ correct 2 weeks ago.
Unfortunately, The sorting issue is BACK in PowerApps Studio version 3.24081.
Typical Power Platform regression errors - seems to happen  EVERY TIME they fix a bug - it's never rolled into the development of the following version...

J.

**Comment by Reinhard-S** [comment]
Hi, are there any news regarding this topic?

@rarattay, we would like to get some insights how and when your upgrades on the components are deployed as it's not related to the deployment cycle of the creator kit solutions. I assume that the bugfix was conducted directly within the react web components provided through a CDN (fluentui-react.js)?

Thank you,
Reinhard
