### ISSUE TITLE
[Creator Starter Kit] BUG: Details List Date Formatting Issue

### ISSUE THREAD

**Issue by daniel-alifano** [microsoft/powercat-creator-kit#54]
Using the details list is it possible to change the date format of the Powercat details list.
Regional Site settings has been set correctly to Australia, however details list ignores this setting and displays as US date format.
Any help will be appreciated.

1. Add Australian formatted sharepoint list to the details list

**Expected behavior**
Match formatting of datasource or option to change date formats

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
![git](https://user-images.githubusercontent.com/31948694/177240669-7aab7558-e4bc-4214-97bf-f55b94730fc3.PNG)

**Comment by scottdurow** [comment]
Hi @daniel-alifano
Thanks for helping with the Creator Kit! 😊
The code component date format comes from the browser language set (or OS language if running the native player app) rather than the Regional Site settings. You can change the browser language using **Settings**-> **Language**.

An alternative is to explicitly set the date form using `AddColumn()` and `Text()` to format the date.
1. On the DetailsList record datasource, change it to be:
```
AddColumns('SharePointList',"CreatedFormatted",Text('Created',DateTimeFormat.ShortDate,"en-AU"))
```
2. Add the `DateFieldFormatted` column to the list of Fields on the FluentDetailsList control:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/2871121/177620613-cedd13e2-c180-432a-bd1a-c9d4cb9d638f.png">

3. Add the new column to the list of columns on the FluentDetailsList control. E.g:
```
Table(...other columns...,{ColName:"CreatedFormatted",ColDisplayName:"Created",ColWidth:200})
```
More info on Text formatting of dates - https://docs.microsoft.com/en-us/power-platform/power-fx/reference/function-text#date-and-time-placeholders

Perhaps the controls would be better to use the ContentLanguage property to control the formatting of dates - or maybe a format string that could be provided for numeric/date columns. Do you have any suggestions/ideas?

**Comment by daniel-alifano** [comment]
This worked, thank you.
I believe a formatting string would make the most sense, would also allow use of the created on field without the time attached.

Anyone having an issue changing chrome date format can follow here:
https://help.gofmx.com/hc/en-us/articles/115001796651-How-to-Change-Your-Date-Format-to-dd-mm-yy-in-Your-FMX-Site
