### ISSUE TITLE
[Feature] DetailsList paging should show the top of the next page

### ISSUE THREAD

**Issue by denise-msft** [microsoft/powercat-creator-kit#67]
**Is this request for a new component, or additional functionality for an existing component? **
Existing component - DetailsList

**Describe the component and functionality you would like to see in the starter kit**
DetailsList paging - going to the next page should jump to the top of the list when the next page is displayed.

**Additional context**
If this is implemented with Setting the record, that should be explicitly called out in the documentation.

(Reported by Brian during internal Bug Bash July 2022)

**Comment by scottdurow** [comment]
This can be implemented today using the 'SetFocusOnRow' event. So if you had the `InputEvent` property bound to `ctxGridEvent`, in the next page button you would use:
`UpdateContext({ctxGridEvent:"LoadNextPageSetFocusOnRow" & Text(Rand())});`

instead of just:
`UpdateContext({ctxGridEvent:"LoadNextPage" & Text(Rand())});`

This needs to be better documented - and perhaps the behaviour could be controlled by a property on the control.

**Comment by denisem-msft** [comment]
Thanks @scottdurow, we will update the documentation to reflect this. It would be great to consider this as a property to make the controls more accessible to newer users.
