### ISSUE TITLE
[BUG]: ItemDivider set to false renders a blank ContextMenu item

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#68]
**Describe the bug**
If you add a { ItemDivider:false }, a blank item in a ContextMenu or CommandBar will render.
![image](https://user-images.githubusercontent.com/43950360/179270072-0c1ef886-50b8-4397-bdd4-b419ead0b3ed.png)

**To Reproduce**
1. Add a ContextMenu
2. Add a schema that contains a submenu
Table(
{ ItemKey: "new",ItemDisplayName: "New",ItemIconName: "Add"},
{ ItemKey:"printall ",ItemDisplayName:"Print all",ItemIconName:"print",ItemParentKey:"print" },
{ ItemKey:"print-specific",ItemDisplayName:"Print specific pages",ItemIconName:"page",ItemParentKey:"print"},
{ ItemParentKey:"print",ItemDivider:false },
{ ItemKey:"print-autosize",ItemDisplayName:"Auto Size",ItemIconName:"PictureStretch",ItemParentKey:"print",ItemChecked:!!varAutoPlayChecked }
)

**Expected behavior**
If false, the divider should not render anything

**Screenshots**
![image](https://user-images.githubusercontent.com/43950360/179270072-0c1ef886-50b8-4397-bdd4-b419ead0b3ed.png)

(Reported by Mike during internal Bug Bash July 2022)

**Comment by scottdurow** [comment]
If the `ItemDivider` property is set to false, the item is considered a normal menu item instead of a divider, and so it expects the `ItemDisplayName` and/or `ItemIconName` as well. In the situation described, the menu item is blank because `ItemDisplayName` is blank.

So the logic would be to only render the item if:
`(ItemDivider = true) || !IsBlank(ItemDisplayName) || !IsBlank(ItemIconName)`

**Comment by denisem-msft** [comment]
Seems like sufficient documentation would be a good resolution for this over preventing this behavior in the component. I'll mark this as a doc update.

**Comment by denisem-msft** [comment]
Notes have been added to the ContextMenu and CommandBar documentation and will be available in the next release.
