### ISSUE TITLE
[Feature] Calendar

### ISSUE THREAD

**Issue by denisem-msft** [microsoft/powercat-creator-kit#80]
**How to promote this component**
Please give a thumbs up reaction to this post to promote this backlog item. You may also share your usage scenario in the comments.

**Component description**
The calendar control lets people select and view a single date or a range of dates in their calendar. It’s made up of 3 separate views: the month view, year view, and decade view.

![image](https://user-images.githubusercontent.com/43950360/182409370-3bd39be0-8b7a-4d03-82e9-badaba4f5706.png)

[Tooltip Fluent UI documentation](https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar)

**Comment by AstroNorman** [comment]
<img width="458" alt="date and time information" src="https://user-images.githubusercontent.com/106515086/184592001-8aa8762b-b688-4bce-b220-b3a59f9948c7.PNG">
Currently using the calendar component from the canvas. Would be great if the component allow me to change:
- font: size, weight, color
- border: size, on-hover color

**Comment by pstrindlund** [comment]
The main thing that is missing in the FluentUI version of the calendar control is the ability to define "DateFormat". What is called "Format" property in the classic Date Picker control.

It looks like the preview version of this control is also missing this (https://docs.microsoft.com/en-us/power-platform/guidance/creator-kit/calendar)

Please add DateFormat property into this calendar control so that we can get rid of the classic calendar control when we need to display non-US formatted dates.
